// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoWorld.Models;

public partial class Countrylanguage
{
    public string CountryCode { get; set; }

    public string Language { get; set; }

    public string IsOfficial { get; set; }

    public decimal Percentage { get; set; }

    public virtual Country CountryCodeNavigation { get; set; }
}